drm/msm/sde: Mark _sde_hw_rot_reg_dump as __maybe_unused
Subsequent to 9f5295e ("drm/msm: skip sde_dbg compilation altogether"),
this function becomes unused with sde_dbg compiled out. Mark it as such
to silence the following compiler warning:

../drivers/gpu/drm/msm/sde/sde_hw_rot.c:69:13: error: unused function '_sde_hw_rot_reg_dump'
      [-Werror,-Wunused-function]
static void _sde_hw_rot_reg_dump(void *ptr)
            ^

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>